# Generated by Django 3.2.5 on 2021-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Infosys', max_length=100),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='emp',
        ),
    ]
