# Generated by Django 3.2.5 on 2021-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Timeline',
            field=models.DateField(null=True),
        ),
    ]
