# Generated by Django 3.2.5 on 2021-08-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_task_timeline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Timeline',
            new_name='timeline',
        ),
        migrations.AlterField(
            model_name='task',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task', to='app1.employee'),
        ),
    ]
