# Generated by Django 3.2.5 on 2021-08-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210810_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee',
            field=models.ManyToManyField(db_table='emp_project', to='app1.Employee'),
        ),
    ]
